name: Project Influence  Schedule Save Crawler data
on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Fill reason here!!!!!!"
        required: false
jobs:
  save-input-data:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: "InfluenceBooking/crawler"
          token: ${{ secrets.GH_PAT }}
          ref: "main"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - name: Install dependencies
        run: |
          npm install
      - name: Run script
        run: |
          node ./src/write-input-data.js

  save-crawler-instagram:
    needs: save-input-data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          python ./src/crawler/crawlInstagram.py

  save-crawler-youtube:
    needs: save-input-data
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          node ./src/crawl-yt-profile.js

  save-crawler-facebook:
    needs: save-input-data
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          node ./src/crawl-fb-profile.js

  save-crawler-tiktok:
    needs: save-input-data
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run: |
          node ./src/crawl-tt-profile.js
