name: Project Influence  Schedule Save Crawler data
on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Fill reason here!!!!!!"
        required: false
jobs:
  save-input-data:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: "InfluenceBooking/crawler"
          token: ${{ secrets.GH_PAT }}
          ref: "main"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
      - name: Install dependencies
        run: |
          npm install
      - name: Run script
        run: |
          echo "GET_INFLUENCERS_URL=https://api-dev.theinfluence.ai/api/influencers/social-links" >> .env
          node ./src/write-input-data.js
      # - name: Run script Instagram
      #   run: |
      #     node ./src/crawl-ig-profile.js

      - name: Run script Facebook
        run: |
          node ./src/crawl-fb-profile.js

      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.13"
      # - name: Install dependencies
      #   run: |
      #     ls
      #     python -m venv py-crawl
      #     source py-crawl/bin/activate
      #     pip install -r requirements.txt
      #     python crawlInstagram.py
      # - name: Run script Instagram
      #   run: |
      #     python ./crawlInstagram.py

  # save-crawler-youtube:
  #   needs: save-input-data
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run script
  #       run: |
  #         node ./src/crawl-yt-profile.js

  # save-crawler-facebook:
  #   needs: save-input-data
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run script
  #       run: |
  #         node ./src/crawl-fb-profile.js

  # save-crawler-tiktok:
  #   needs: save-input-data
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run script
  #       run: |
  #         node ./src/crawl-tt-profile.js
